version: '3.8'
services:
  backend: 
    image: moderatorregistry.azurecr.io/moderator
    restart: unless-stopped
    ports:
      - 8080:8080

  frontend:
    image: moderatorregistry.azurecr.io/moderator-frontend
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - backend
